image:
  name: texlive/texlive:latest
  entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]

build_and_deploy: 
  script:
    - cd docs/presentation_17_03_23
    - pdflatex main.tex
    - cd ../rapportFinal
    - pdflatex main.tex
  only:
    refs:
      - merge_request
      - develop
      - main
    changes:
      - docs/**/*
      - .gitlab-ci.yml
  after_script:
    - cat ./docs/main.log
  artifacts:
    paths:
      - ./docs/presentation_17_03_23/main.pdf
      - ./docs/rapportFinal/main.pdf
