image:
  name: texlive/texlive:latest
  entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]

build_and_deploy: 
  script:
    - cd ./docs/rapportFinal
    - pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -recorder main.tex && biber "main.bcf" && pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -recorder main.tex && pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -recorder main.tex
    - cd ../presentation_17_03_23
    - pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -recorder main.tex && pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -recorder main.tex
    
  only:
    refs:
      - merge_request
      - develop
      - main
    changes:
      - docs/**/*
      - .gitlab-ci.yml
  artifacts:
    paths:
      - ./docs/presentation_17_03_23/main.pdf
      - ./docs/rapportFinal/main.pdf
